# Generated by Django 5.2.8 on 2025-11-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'Libros'},
        ),
    ]
