# Generated by Django 5.2.8 on 2025-11-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_alter_libro_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
