# Generated by Django 5.2.8 on 2025-11-27 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_autor_slug_categoria_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='slug',
        ),
    ]
