# Generated by Django 5.2.8 on 2025-11-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_alter_libro_options_autor_slug_categoria_slug'),
    ]

    operations = [
    ]
